# To use:
#
#   $ micromamba env create -f environment.yml  # `conda` works too for this command
#   $ micromamba activate anneal-dev
#
name: anneal-dev
channels:
  - conda-forge
dependencies:
  - meson
  - cmake
  - ninja
  - pkg-config
  - openblas
  - python>=3.10
  - jupytext
  - jupyterlab
  # For R tests
  - r-base==4.2.2
  - xorg-libxrender
  - libiconv
  - libtiff
  - r-essentials
  - r-cairo
  - r-devtools
  - r-languageserver
  - r-irkernel
  - jupyterlab
  - r-tidyverse
  - r-microbenchmark
  - r-gensa
  - r-pracma
  - r-httpgd
  - radian
  - pdm
