[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "anneal"
description = "A package for various annealing and quenching techniques"
authors = [
    { name = "Rohit Goswami",   email = "rgoswami@ieee.org" },
    { name = "Ruhila S",         email = "ruhila@ieee.org" },
    { name = "Amrita Goswami",   email = "amrita@hi.is" },
    { name = "Sonaly Goswami",   email = "sonaly@iitk.ac.in" },
    { name = "Debabrata Goswami", email = "dgoswami@iitk.ac.in" },
]
maintainers = [
    { name = "Rohit Goswami", email = "rgoswami@ieee.org" },
    { name = "Ruhila S",       email = "ruhila@ieee.org" },
    { name = "Amrita Goswami", email = "amrita@hi.is" },
]
version = "0.2.0"
requires-python = ">=3.10"
license = "MIT"
readme = "README.md"
keywords = ["optimization", "algorithms"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "click>=8.1.3",
    "numpy>=1.24.1",
    "matplotlib>=3.6.3",
    "tqdm>=4.64.1",
    "probsamplers>=0.1.0",
    "eindir>=0.2.0,<0.3",
]

[project.optional-dependencies]
plotter = ["pandas>=1.5.3", "matplotlib>=3.6.3"]
testing = ["pytest>=8", "pytest-cov>=4.1"]

[project.urls]
"Homepage"   = "https://github.com/HaoZeke/anneal"
"Bug Tracker" = "https://github.com/HaoZeke/anneal/issues"

[tool.maturin]
features      = ["python"]
module-name   = "anneal._core"
python-source = "python"
